# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HelloDjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
